name: Build Pyromod

on:
  push:
    branches: master
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches: master
    paths-ignore:
    - '**/*.md'

jobs:
  arch64:
    strategy:
      fail-fast: false
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build pyromod
      run: sh .github/scripts/makepyromod-cm2.sh test $HOME
