name: Build Pyromod

on:
  push:
    branches: master
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches: master
    paths-ignore:
    - '**/*.md'

jobs:
  arch64:
    strategy:
      fail-fast: false
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build pyromod
      run: |
        MOD_VERSION="$(jq .version mod.json | tr -d \")"
        MOD_NAME="$(jq .name mod.json | tr -d \")"
        sh .github/scripts/makepyromod.sh ${MOD_NAME} ${MOD_VERSION} ${HOME}
        rm ${HOME}/${MOD_NAME}*.*

  build-pyromod:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses:  0ad-matters/gh-action-build-pyromod@trunk
        id: build-pyromod

