name: checkrefs
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - master
    paths:
    - 'art/**'
    - 'maps/**'
    - 'simulation/**'
  pull_request:
    branches:
    - master
    paths:
    - 'art/**'
    - 'maps/**'
    - 'simulation/**'

jobs:
  checkrefs:
    runs-on: bullseye
    steps:
    - uses: actions/checkout@v3
    - run: |
        ERRLOG="${GITHUB_WORKSPACE}/errlog.txt"
        cd /0ad/source/tools/entity
        python3 ./checkrefs.py -m "${GITHUB_WORKSPACE}" -tax 2> $ERRLOG
        cat $ERRLOG
        grep -i error $ERRLOG && exit 1
        grep -i warning $ERRLOG && exit 1
