name: checkrefs
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - master
    paths:
    - 'art/**'
    - 'maps/**'
    - 'simulation/**'
    - '**/checkrefs.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'art/**'
    - 'maps/**'
    - 'simulation/**'
    - '**/checkrefs.yml'

jobs:
  checkrefs:
    runs-on: bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Run checkrefs.py
        run: |
          ERRLOG="${GITHUB_WORKSPACE}/errlog.txt"
          cd /0ad/source/tools/entity
          python3 ./checkrefs.py -m "${GITHUB_WORKSPACE}" -tax 2> $ERRLOG
          LOG_CONTENTS=$(cat $ERRLOG)
          if [ -z "$LOG_CONTENTS" ]; then
            exit 0
          fi
          echo $LOG_CONTENTS
          exit 1

      - uses: tj-actions/changed-files@v35
        id: changed-files
        with:
          separator: ","
      - name: Check changed file names
        run: |
          IFS=$',' read -a changed_file_array <<< "${{ steps.changed-files.outputs.all_changed_files }}"
          wrong_file_array=()
          for file in "${changed_file_array[@]}"; do
            [[ "$file" =~ ^maps/(random|scenarios|skirmishes)/[^/]+$ ]] || continue
            [[ $(basename "${file%.*}") =~ ^[0-9a-z_]+$ ]] || wrong_file_array+=("$file")
          done
          if [ ${#wrong_file_array[@]} -gt 0 ]; then
            echo "::error:: Regex for file names doesn't match: ${wrong_file_array[@]} "
            exit 1
          fi
