name: checkrefs
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - master
    paths:
    - 'art/**'
    - 'maps/**'
    - 'simulation/**'
    - '**/checkrefs.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'art/**'
    - 'maps/**'
    - 'simulation/**'
    - '**/checkrefs.yml'

jobs:
  checkrefs:
    runs-on: bullseye
    steps:
      - uses: actions/checkout@v3
      - name: Run checkrefs.py
        run: |
          ERRLOG="${GITHUB_WORKSPACE}/errlog.txt"
          cd /0ad/source/tools/entity
          python3 ./checkrefs.py -m "${GITHUB_WORKSPACE}" -tax 2> $ERRLOG
          LOG_CONTENTS=$(cat $ERRLOG)
          if [ -z "$LOG_CONTENTS" ]; then
            exit 0
          fi
          echo $LOG_CONTENTS
          exit 1
      - uses: tj-actions/changed-files@v35
        id: changed-files-glob
        with:
          separator: ','
          files: |
            **/maps/{random,skirmishes,scenarios}/*.{js,json,pmp,xml}
      - name: Check changed file names
        run: |-
          IFS=$',' read -ra filesArray <<< "${{ steps.changed-files-glob.outputs.all_changed_files }}"
          errorFiles=()
          for file in "${filesArray[@]}"; do
            [[ $(basename "${file%.*}") =~ ^[0-9a-z_]+[0-9a-z]$ ]] || errorFiles+=("$file")
          done
          if [ ${#errorFiles[@]} -gt 0 ]; then
            echo "::error:: Regex for file names doesn't match: ${errorFiles[@]}"
            exit 1
          fi
